# Animal emoji -> sound dictionary
animal_sounds = {
    "🐱": "Meow Meow",
    "🐶": "Woof Woof",
    "🐭": "Squeak",
    "🐹": "Squeak Squeak",
    "🐰": "Squeak / Thump",
    "🦊": "Ring-ding / Growl",
    "🐻": "Growl",
    "🐼": "Bleat / Growl",
    "🐨": "Murmur",
    "🐯": "Roar",
    "🦁": "Roarrr",
    "🐮": "Moo Moo",
    "🐷": "Oink Oink",
    "🐽": "Snort",
    "🐸": "Ribbit",
    "🐵": "Oo-oo-aa-aa",
    "🙈": "Chatter",
    "🙉": "Chatter",
    "🙊": "Chatter",
    "🐔": "Cluck Cluck",
    "🐤": "Cheep Cheep",
    "🐦": "Tweet Tweet",
    "🐧": "Honk / Squawk",
    "🦆": "Quack Quack",
    "🦅": "Screech",
    "🦉": "Hoot",
    "🦇": "Screech",
    "🐺": "Howl",
    "🐗": "Grunt",
    "🐴": "Neigh",
    "🦄": "Neigh / Whinny",
    "🐝": "Buzz",
    "🐛": "Crawl / Wiggle",
    "🦋": "Flutter",
    "🐌": "Slither",
    "🐞": "Buzz",
    "🐜": "Chirp",
    "🦗": "Chirp",
    "🕷️": "Hiss / Crawl",
    "🦂": "Hiss",
    "🐢": "Hiss / Crawl",
    "🐍": "Hiss",
    "🦎": "Hiss / Crawl",
    "🐙": "Squish",
    "🦑": "Squish",
    "🦀": "Click",
    "🦞": "Click",
    "🦐": "Click",
    "🦪": "Splash",
    "🐠": "Blub Blub",
    "🐟": "Blub Blub",
    "🐡": "Blub Blub",
    "🐬": "Click / Chirp",
    "🐳": "Whistle",
    "🐋": "Whistle",
    "🦈": "Chomp",
    "🐊": "Snap",
    "🐆": "Growl",
    "🐅": "Roar",
    "🦓": "Neigh / Whinny",
    "🦌": "Bleat",
    "🦬": "Moo / Grunt",
    "🐘": "Trumpet",
    "🦏": "Grunt",
    "🦛": "Grunt",
    "🐪": "Grunt / Hum",
    "🐫": "Grunt / Hum",
    "🦙": "Hum",
    "🦒": "Bleat",
    "🐃": "Moo",
    "🐂": "Moo",
    "🐎": "Neigh",
    "🦔": "Snuffle",
    "🦇": "Screech",
    "🦥": "Murmur",
    "🦦": "Chatter",
    "🦨": "Scream",
    "🦘": "Chortle",
    "🦡": "Growl",
}

print('Enter an animal emoji (type x to quit):')

while True:
    emoji = input("\nEmoji: ").strip()  # starts prompt on a new line
    
    if emoji.lower() == 'x':
        print("Program Ended")
        break

    sound = animal_sounds.get(emoji, "Unknown sound")
    print(sound)  # each sound on its own line
